eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost



# logging:
#   file:
#     name: C:/Users/sparrow/Downloads/Logs/loggers.log


spring:
  zipkin:
    base-url:http://localhost:9411

# springdoc:
#   swagger-ui:
#     path: /swagger-ui.html
#   api-docs:
#     path: /api-docs
#   show-actuator: true



management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
